add condition check, adjust comment and echo

diff --git a/script1 b/script1
--- a/script1
+++ b/script1
@@ -1,18 +1,28 @@
 #!/bin/bash
 
+# Check if at least 2 parameters were provided
+if [ "$#" -lt 2 ]; then
+    echo "Error: At least 2 parameters are required."
+    exit 1
+fi
+
 # Ask user for n
 read -p "Enter the value of n: " n
 
 # If both n and number of arguments equal to 2, print only the second parameter and exit
-if test "$n" -eq 2 && test "$#" -eq 2; then
-    echo "The second parameter is '$2'."
+if test "$n" -eq 2; then
+    echo "The 2-nd parameter exits and the value is '$2'."
     exit 0
 fi
 
-# If n != number of arguments, check if the n-th parameter exists
+# If n != number of arguments
+# The number of arguments is greater or equal n, print the second and n-th parameter
 if test "$#" -ge "$n"; then
-    echo "The ${n}-th parameter is '${!n}'."
+    echo "The 2-nd parameter exits and the value is '$2'."
+    echo "The ${n}-th parameter exits and the value is '${!n}'."
+# The number of arguments is lower than n, print the second parameter and the error
 else
+    echo "The 2-nd parameter exits and the value is '$2'."
     echo "The ${n}-th parameter does not exist (only $# parameters provided)."
     exit 1
 fi
